
package pl.polsl.seatreservation.view;

import pl.polsl.seatreservation.controller.SeatReservation;

/**
 *
 * @author Piotr Kuźnik
 * @version 1.0
 */
public class ReservationWindow extends javax.swing.JFrame {

    /**
     * Main controller app
     */
    private final SeatReservation controller;
    
    /**
     * Creates new form ReservationWindow
     * @param controller Main controller app
     */
    public ReservationWindow(SeatReservation controller) {
        initComponents();
        
        this.controller = controller;
        
        this.quantityOfChairsInColumnHall.setText("" + controller.getHeightCinemaHall());
        this.quantityOfChairsInRowHall.setText("" + controller.getWidthCinemaHall());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantityOfChairsInRowHall = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfReservationChairsInHall = new javax.swing.JList<>();
        quantityOfChairsInColumnHall = new javax.swing.JTextField();
        applySettingsButton = new javax.swing.JButton();
        quantintyToReservedField = new javax.swing.JTextField();
        reservedButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quantityOfChairsInRowHall.setToolTipText("Ilość krzeseł w rzędzie");

        jScrollPane1.setViewportView(listOfReservationChairsInHall);

        quantityOfChairsInColumnHall.setToolTipText("Ilość rzędów");

        applySettingsButton.setText("Ustaw");
        applySettingsButton.setActionCommand("");
        applySettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applySettingsButtonActionPerformed(evt);
            }
        });

        quantintyToReservedField.setToolTipText("Ilośc miejsc do zarezerwowania");

        reservedButton.setText("Rezerwuj");
        reservedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservedButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Konfiguracja sali kinowej");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantityOfChairsInRowHall, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quantityOfChairsInColumnHall, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(applySettingsButton))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantintyToReservedField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservedButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityOfChairsInRowHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityOfChairsInColumnHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applySettingsButton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quantintyToReservedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservedButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Execute action after on click settings button
     * 
     * @param evt ActionEvent as java.awt.event.ActionEvent 
     */
    private void applySettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applySettingsButtonActionPerformed
        int sizeX = Integer.parseInt(this.quantityOfChairsInRowHall.getText());
        int sizeY = Integer.parseInt(this.quantityOfChairsInColumnHall.getText());
        this.controller.setHallSize(sizeX, sizeY);
    }//GEN-LAST:event_applySettingsButtonActionPerformed

    /**
     * Execute action after on click reserved button
     * 
     * @param evt ActionEvent as java.awt.event.ActionEvent 
     */
    private void reservedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservedButtonActionPerformed
        int quantityOfChairs = Integer.parseInt(this.quantintyToReservedField.getText());
        this.controller.reserveQuantityOfChairs(quantityOfChairs);
        
        
        listOfReservationChairsInHall.setModel(this.controller.renderGraficToModelList());
    }//GEN-LAST:event_reservedButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applySettingsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listOfReservationChairsInHall;
    private javax.swing.JTextField quantintyToReservedField;
    private javax.swing.JTextField quantityOfChairsInColumnHall;
    private javax.swing.JTextField quantityOfChairsInRowHall;
    private javax.swing.JButton reservedButton;
    // End of variables declaration//GEN-END:variables
}
